export const RegionTypes = {
  CHANGE_REGION: "CHANGE_REGION",
};

export const StatsTypes = {
  UPDATE_SUMMONER: "UPDATE_SUMMONER",
  UPDATE_MATCH_HISTORY: "UPDATE_MATCH_HISTORY",
  UPDATE_LOADING: "UPDATE_LOADING",
  RESET_SEARCH: "RESET_SEARCH",
  SHOW_MORE: "SHOW_MORE",
  MAX_MATCHES: "MAX_MATCHES",
  UPDATE_MATCHES: "UPDATE_MATCHES",
};

export const DDragonTypes = {
  UPDATE_CHAMPS: "UPDATE_CHAMPS",
  UPDATE_VERSION: "UPDATE_VERSION",
  UPDATE_QUEUES: "UPDATE_QUEUES",
  UPDATE_SUMMONERS: "UPDATE_SUMMONERS"
};
