export const RegionTypes = {
  CHANGE_REGION: "CHANGE_REGION",
};

export const StatsTypes = {
  UPDATE_SUMMONER: "UPDATE_SUMMONER",
  UPDATE_MATCH_HISTORY: "UPDATE_MATCH_HISTORY",
  UPDATE_LOADING: "UPDATE_LOADING",
  RESET_SEARCH: "RESET_SEARCH",
  SHOW_MORE: "SHOW_MORE",
  MAX_MATCHES: "MAX_MATCHES"
};
